id: P02D29113
initial_creation_type: input
source_metadata:
  title: Dezhung Rinpoche Series
  language: bo
  description: 'Texts by and about Dezhung Rinpoche (sde gzhung rin po che, 1906–1987),
    one of the most important Sakya teachers of recent times renowned for his exceptional
    erudition and nonsectarianism:'
  volume:
    cad4c73806cf49cd8094120451eb808e:
      title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
      parent: Long Life Prayers
created_at: '2022-02-28T22:49:33.111879'
last_modified_at: '2022-02-28T22:49:33.111882'
